- jobs/atc/spec
The v4.1.0 release notes (https://concourse-ci.org/download.html#v410) say that local users can have plaintext passwords specified, but the BOSH release spec text doesn't reflect that - it *only* mentions bcrypt'd hashes.
The CLI help text *does* reflect this, which is presumably what the v4.1.0 release notes were referring to:
```
$ ./concourse_darwin_amd64 web --help 2>&1 | grep -m1 add-local-user
--add-local-user=USERNAME:PASSWORD                            List of username:password combinations for all your local users. The password can be bcrypted - if
```
This commit brings those 2 texts (mostly) into line by updating the atc spec description and making it clear that `user:plaintext-pass` tuples are acceptable.
Related: concourse/concourse#2602
> `add_local_users` passwords can be plain text

- jobs/web/spec
added missing flag --vault-max-lease/environment variable `CONCOURSE_VAULT_MAX_LEASE`
fixes #10
Signed-off-by: Mike Lloyd <mike@reboot3times.org>
> added vault.max_lease.

- jobs/web/templates/pre_start.erb
- jobs/web/templates/pre_start.erb.tmpl
- jobs/worker/templates/pre_start.erb
- tmpl/create_env_files.erb.tmpl
- tmpl/create_env_files_spec.rb
This addresses the issue described at #19
First commit erects some unit tests around the ruby helpers used by `envgen` so that I can make the second commit with confidence.
The second commit adds two lines after the creation of each env file:
* `chmod 0600 <filename>`
* `chown vcap:vcap <filename>`
so that the files look like:
```
$ ls -lt /var/vcap/data/jobs/web/*/config/env
total 24
-rw------- 1 vcap vcap 1675 Mar  9 17:31 CONCOURSE_TSA_HOST_KEY
-rw------- 1 vcap vcap 1675 Mar  9 17:31 CONCOURSE_SESSION_SIGNING_KEY
-rw------- 1 vcap vcap  381 Mar  9 17:31 CONCOURSE_TSA_AUTHORIZED_KEYS_0
-rw------- 1 vcap vcap 1679 Mar  9 17:31 CONCOURSE_POSTGRES_CLIENT_KEY
-rw------- 1 vcap vcap 1188 Mar  9 17:31 CONCOURSE_POSTGRES_CLIENT_CERT
-rw------- 1 vcap vcap 1147 Mar  9 17:31 …
```
> modify env file permissions and ownership to 0600 / vcap:vcap

- jobs/worker/spec
- jobs/worker/templates/concourse.service
- jobs/worker/templates/concourse_start.erb
- jobs/worker/templates/concourse_stop.erb
- jobs/worker/templates/ctl.erb
concourse/concourse#3613
Garden manages the cgroups for the containers it spawns, systemd thinks it's the only manager of cgroups and will move cgroups around as it deems fit. 
Solution is to let systemd know that Concourse (which is the parent of garden) will be managing it's own cgroups by installing a service with `Delegate=yes`
> register concourse worker as a systemd service

- jobs/bbr-atcdb/spec
- jobs/bbr-atcdb/templates/config.json.erb
- jobs/web/spec
- The web job provide it's db connection info as bosh links
- The bbr-atcdb job consumes from the web job if available
Thoughts?
For https://github.com/concourse/concourse/issues/2332
> Use bosh links for getting db info for bbr

- jobs/worker/templates/ctl.erb
In worker/bin/ctl.erb a check for systemd sets IS_RUNNING_SYSTEMD=true. Prior to that IS_RUNNING_SYSTEMD is initialized to 'false'. In the conditional to check the state `[ -n "${IS_RUNNING_SYSTEMD}" ]` is used, which fails due to the prior initialization.
This is required to deploy concourse via docker-cpi. Which is very useful way to run it locally.
> Fix logic for running worker without systemd

- dev/vbox/topgun
- jobs/bbr-atcdb/spec
- jobs/bbr-atcdb/templates/config.json.erb
Previously, `bbr-atcdb` was trying to find properties that don't exist ("postgre**ss**ql")
https://github.com/concourse/concourse-bosh-release/blob/b8dc05d9c558939debbc5e83ee730abbc01e1f4d/jobs/bbr-atcdb/templates/config.json.erb#L50-L56
in the job that exposes them https://github.com/concourse/concourse-bosh-release/blob/b8dc05d9c558939debbc5e83ee730abbc01e1f4d/jobs/web/spec#L30-L40
This meant that the properties would never be found.
fixes #34 
Next steps:
> Improve use of BOSH links in bbr-atcdb config template

- jobs/web/templates/bpm.yml.erb
CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER is in the spec but not in the bpm job.
> Adding CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
* allow to configure env variable CONCOURSE_GARDEN_NETWORK_POOL
* required if you want to use Concourse, inside the default network pool
range 10.254.0.0/22
> Make Garden network pool configurable

- SHIPPING.md
Hey, while going through the process of shipping 4.2.6, I noticed that the
current instructions were not entirely complete - the process is slightly more
involved than just triggering promote-job.
This commit is about making more clear what the steps are once you're in
the process of preparing a patch.
Wdyt?
thx!
> update SHIPPING.md nodes to account for version bumps

- README.md
Currently this is knowledge stored in a few individual heads. Now it's
stored where others may see it or at least sumble across it when working
with the bosh release.
[This comment] is what prompted me to make this addition.
[This comment]:https://github.com/concourse/concourse-bosh-release/pull/63#pullrequestreview-311948056
> Update README with how to use scripts/generate-job-templates

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
- jobs/worker-windows/spec
- jobs/worker-windows/templates/env.ps1.erb
- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
In [concourse/concourse#4707](https://github.com/concourse/concourse/pull/4707) we made the timeout applied to requests originating from either `atc` or `worker` configurable via the `--garden-request-timeout` flags (on both `worker` and `web`).
This PR adds configuration for such flag for the BOSH release.
> Add CONCOURSE_GARDEN_REQUEST_TIMEOUT config

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Got the naming wrong for the compression flag in https://github.com/concourse/concourse-bosh-release/pull/64
CI found the error: https://ci.concourse-ci.org/teams/main/pipelines/release-5.5.x/jobs/bosh-check-props/builds/66
> Rename NewRelic compression flag

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Adding
```
CONCOURSE_MAIN_TEAM_CF_SPACE_DEVELOPER
CONCOURSE_MAIN_TEAM_CF_SPACE_AUDITOR
CONCOURSE_MAIN_TEAM_CF_SPACE_MANAGER
```
to spec
> add main team flags for cf auth space roles

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
To address failures like https://nci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-check-props/builds/41.
> add vault namespace param

- jobs/web/spec
The AME API v1 is deprecated for more details check [this post](https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380/4)
Concourse team already updated client in v5.8.0
> Use Let's Encrypt ACME API v2

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
- jobs/worker/templates/env.sh.erb.tmpl
- jobs/worker/templates/garden.ini.erb
This enables configuration of the garden `config.ini` as documented here: https://concourse-ci.org/concourse-worker.html#configuring-gdn-server
Sample results after configuration:
```
<...snip...>
export CONCOURSE_GARDEN_CONFIG=/var/vcap/jobs/worker/config/garden.ini
<...snip...>
[server]
...garden settings here...
<...snip...>
root        4355       1  0 18:37 ?        Ss     0:00 /bin/bash /var/vcap/jobs/worker/bin/concourse_start
root        4380    4355  0 18:37 ?        Sl     0:00  \_ /var/vcap/packages/concourse/bin/concourse worker
root        4496    4380  0 18:37 ?        Sl     0:01      \_ gdn --config /var/vcap/jobs/worker/config/garden.ini server --bind-ip 127.0.0.1 --bind-port 7777 --depot /var/vcap/data/worker/work/depot --properties-path /var/vcap/data/worker/work/garde …
```
> Support setting garden config.ini

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Signed-off-by: TJ Higgins <tj@architect.io>
blocked by: https://github.com/concourse/concourse/pull/5432
> Fix typo for COMPONENT_RUNNER_INTERVAL

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
concourse/concourse#5421
I decided to make the spec entry be the plural "limits" becase we will
definitely be adding support for specifying multiple limits separated by
commas in the future, and I don't want to have to change the parameter name at
that point.
> add `--concurrent-request-limit`

- jobs/web/spec
- jobs/worker/spec
We are [changing to a stricter version of the `go-flags` library](https://github.com/concourse/concourse/pull/5429/commits/a1f0e741c88a6b9ed71b6a8c8b15ba422d4f3152#diff-37aff102a57d3d7b797f152915a6dc16R129), which means that the concourse binary [will fail if any invalid env var configuration is passed](https://github.com/concourse/concourse/pull/5429/commits/1401898acc9b0927c36378a83a39ae228999f3c7#diff-d4becb815d0052a5c40f051b44a8e4f2R32-R34). This PR is necessary because it addresses two spots where the bosh release has been setting env vars to invalid values by default.
> ensure no invalid env vars

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Following @vito's [comment](https://github.com/concourse/concourse-bosh-release/pull/97#discussion_r420126963).
> use a map for `--concurrent-request-limit`

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
This feature was added to the web command in
https://github.com/concourse/concourse/pull/5192/. Adding flag to BOSH release for
parity.
> Make CONCOURSE_ENABLE_RERUN_WHEN_WORKER_DISAPPEARS configurable

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
See https://github.com/concourse/concourse/pull/5013, further documentation in https://github.com/concourse/docs/pull/292.
This allows more detailed customization of how the Vault credential manager looks for team- and pipeline-dependent secrets.
Signed-off-by: Alexander Gurney <alexander_gurney@cable.comcast.com>
> jobs/web: Add Vault lookup templates flag

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
- jobs/web/templates/pre_start.erb
Fixed the web spec from `conjur.appliance_interval` to `conjur.appliance_url`.
Also added a web spec for `conjur.ssl_certificate` so you can pass the certificate in directly instead of providing it as a file.
> Conjur appliance url config

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
This PR replaces https://github.com/concourse/concourse-bosh-release/pull/110. It adds the `max-checks-per-second` flag that was added in the v6.3.0 release.
> Add max checks flag for v6.3.0

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
The feature is now always on because it is no longer experimental.
> remove flag to enable archiving pipeline feature

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
CONCOURSE_TSA_GARDEN_REQUEST_TIMEOUT was added in
https://github.com/concourse/concourse/pull/5845/. This PR makes it configurable in the web spec.
> web: add CONCOURSE_TSA_GARDEN_REQUEST_TIMEOUT

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
Part of the PR concourse/concourse#5911, which addresses issue concourse/concourse#5407.
* replace useContainerd and useHoudining with ~~runtime.type~~ runtime
* remove CONCOURSE_CONTAINER_NETWORK_POOL - this is covered by CONCOURSE_GARDEN_NETWORK_POOL and CONCOURSE_CONTAINERD_NETWORK_POOL
* add support for finalized containerd flags
**Note to reviewer** 
I have not been able to verify how BOSH [templates](https://bosh.io/docs/jobs/#templates) work for spec values that can be arrays e.g. garden.dns_servers, containerd.dns_servers.
For example, `garden.dns_servers` in the worker spec can be provided multiple values, and is being referenced in `env.sh.rb` with the following:
```
<% if_p("garden.dns_servers") do |v| -%>
export CONCOURSE_GARDEN_DNS_SERVER=<%= esc(env_flag(v)) %>
<% end -%> …
```
> add support for new containerd flags

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
**Part of:** concourse/concourse#5984
**Changed in this PR**
The CONCOURSE_CONTAINERD_INIT_BIN needs to point to /var/vcap/packages/concourse/bin/init specifically on BOSH when running containerd.
This should only be set when using containerd as the runtime. Currently, that means checking if the runtime property is set to "containerd" explicitly. 
In the future when the concourse binary will default to containerd when no runtime property is set we also need to check if runtime is nil.
**Notes to reviewer**
This will be easier to test with the `bosh-template` gem.
`gem install bosh-template`
**Scenario 1**
`bosh-template jobs/worker/templates/env.sh.erb --context '{"id":"abc123-123abc", "properties":{"runtime":"containerd", "containerd": {"init_bin_path":"something"}}}'`
Result:  
`export …
> add CONCOURSE_CONTAINERD_INIT_BIN

- jobs/web/spec
Removing `CONCOURSE_LIDAR_CHECKER_INTERVAL` as the flag was removed in concourse/concourse#6022.
> remove CONCOURSE_LIDAR_CHECKER_INTERVAL

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
also, removes the lidar_checker_interval which was removed from the spec
but not from the template
side note - #123 makes it so that scripts/generate-job-templates will
always produce a diff, which is unfortunate
> add feature flag for instanced pipelines

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
fixes #127 
alternatively if we want to limit the debug flags option we could do sth like
if enable_godebug_cn_matching
GODEBUG: x509ignoreCN=0
to hardcode the name/value pair. WDYT?
> add godebug configs

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
exposing `CONCOURSE_BAGGAGECLAIM_BIND_IP`
this is needed when trying out the experimental p2p volume streaming
> expose baggageclaim bind_ip this would fix #140

- jobs/bbr-atcdb/spec
- jobs/bbr-atcdb/templates/backup.sh.erb
- jobs/bbr-atcdb/templates/config.json.erb.tmpl
- jobs/bbr-atcdb/templates/connection_data.erb
- jobs/bbr-atcdb/templates/connection_data.erb.tmpl
- tmpl/postgres_config.erb.tmpl
fixes concourse/concourse#6588
This PR does two things:
1. Pause the tracker and collector_pipelines components to reduce the
chance of a build finishing while pg_dump is running. Sleep after
pausing the components as well just to be extra safe.
2. Call the bbr backup binary up to three times if it fails. Most likely
cause of failure based on support tickets has been a build
finishing and its sequence table being dropped. We think it's
unlikely for this to be the cause three times in a row within 10s of
each other.
CC @xtremerui
> Make bbr backup more resilent

- jobs/bbr-atcdb/templates/connection_data.erb.tmpl
- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Add the CSP flag from concourse/concourse#6949
Also changed `x_frame_options` to not have a default to ensure it uses the default set in the Concourse binary.
Sneaking in an extra change to fix an issue with the bbr job templates being out of sync. Noticed it when I ran the `generate-job-templates` script.
> Add Content-Security-Policy header to web

- jobs/worker/templates/concourse.service
The bionic stemcell contains systemd v237 which by default gives a limit of 4915 processes to system cgroups. This restriction can cause jobs to fail when under load. So we are reverting to the xenial default of pids.max = max.
We are seeing this pipeline where we have many periodic jobs running at the same time. The limit gets gets exhausted fairly quickly causing random jobs to fail. We have hit this same problem on garden a few months ago. You can find more info on that in [this pivotal tracker story](https://www.pivotaltracker.com/n/projects/1158420/stories/176595591) and [this commit in our bosh release](https://github.com/cloudfoundry/garden-runc-release/commit/8dec786a6bbe25f6ed8910e910b9799fafad1a61). SSH-ing on the concourse worker we can see that the `garden.system` cgroup has …
> Remove systemd process number limit

- jobs/web/templates/bpm.yml.erb
- jobs/web/templates/bpm.yml.erb.tmpl
The "bosh-deployment" attribute breaks with later Prometheus  libraries since dash (-) is not valid attribute character.
> Change metric attribute - to _ for prometheus compatibility

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
for oci_hooks_dir and seccomp_profile
refer to https://github.com/concourse/concourse/pull/8044
> add worker containerd config

- jobs/web/spec
References:
- https://github.com/concourse/concourse/issues/5157
- https://github.com/concourse/concourse/pull/5168
As per the above mentioned PR's it looks like, we forgot to adjust the default value for the checks recycle, meaning that for bosh Concourses, the checks will pile up. Let's remove the default value from this spec and use the default from Concourse source code, if not otherwise specified here.
> Removing default value, as to use the one from the source-code

- jobs/web/spec
@taylorsilva looks like the Shared Secret Template from AWS was copied to Signing Key -> Check Interval. This updates the field to use the description from the Concourse PR adding the functionality.
> nit: update signing key -> check interval description
