concourse/concourse-bosh-release

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Oops, i meant to create a branch for issue/3013 :D
> add enable global resources flag to web spec

- jobs/web/spec
since its introduction in concourse/concourse#4118
> add max-active-tasks-per-worker configuration

- jobs/web/spec
* influxdb batch size/duration and metrics buffer size concourse/concourse#3937
* max db connection pool size concourse/concourse#4232
> add missing job properties

- jobs/web/templates/bpm.yml.erb
Adding option for CONCOURSE_METRICS_BUFFER_SIZE.
The test exists but the code didn't.
> Update for CONCOURSE_METRICS_BUFFER_SIZE

- jobs/web/templates/bpm.yml.erb
- src/envgen/go.mod
looks like there was a ruby syntax error.
> run `scripts/generate-job-templates`

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Config added in [#4009](https://github.com/concourse/concourse/pull/4009)
Signed-off-by: Denise Yu <dyu@pivotal.io>
> Add SECRET_CACHE_DURATION_NOTFOUND to spec

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
- jobs/worker/templates/env.sh.erb
- CONCOURSE_LIDAR_CHECKER_INTERVAL
- CONCOURSE_LIDAR_SCANNER_INTERVAL
- CONCOURSE_LOG_CLUSTER_NAME
- CONCOURSE_TSA_CLUSTER_NAME
- CONCOURSE_TSA_LOG_CLUSTER_NAME
> add missing spec properties:

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Adds
```
CONCOURSE_NEWRELIC_BATCH_SIZE
CONCOURSE_NEWRELIC_BATCH_DURATION
CONCOURSE_NEWRELIC_DISABLE_COMPRESSION
```
to the web spec
From https://github.com/concourse/concourse/pull/4698
> Add NewRelic batch flags

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
> 5.5.x: Rename NewRelic compression flag

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Supports [#4684](https://github.com/concourse/concourse/pull/4684)
Signed-off-by: Denise Yu <dyu@pivotal.io>
> Add Microsoft login properties

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
* Should be re-added when [#4684](https://github.com/concourse/concourse/pull/4684)
is merged
Signed-off-by: Ciro S. Costa <cscosta@pivotal.io>
> Revert addition of Microsoft login configs

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
- jobs/web/templates/pre_start.erb
https://github.com/concourse/concourse/pull/4657
Signed-off-by: Ciro S. Costa <cscosta@pivotal.io>
> Add config for CONFIG_RBAC

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
This reverts commit 619ba79973104541acfb9e1318476090c51a7f09.
> Revert "update cf flags for main team auth"

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
And minor revision to some Vault configs to disambiguate the use of "namespace" in two places.
> Add microsoft auth and conjur creds manager

- jobs/worker-windows/spec
- jobs/worker-windows/templates/env.ps1.erb
> Expose external_garden_url spec property for worker-windows

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
related: https://github.com/concourse/concourse/pull/5043
> jobs/web: add tracing flags

- jobs/web/spec
> updeprecate cf-space-guid

- dev/vbox/setup
Signed-off-by: Jeremy Alvis <jalvis@pivotal.io>
required for https://github.com/concourse/concourse/pull/5255
> add uaa release to vbox for use with topgun tests

- jobs/worker-windows/spec
- jobs/worker/spec
> [#4847] Set default rebalance-interval

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Reverts concourse/concourse-bosh-release#97
> Revert "add `--concurrent-request-limit`"

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Added in https://github.com/concourse/concourse/pull/5887
> add feature flag for across step

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
- jobs/web/templates/pre_start.erb
Needed after concourse/concourse#5998 was merged
Would be pretty *sick* if we just took in a config file à la https://github.com/concourse/concourse/discussions/5891
> Add SAML auth config

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
Flag was added in concourse/concourse#6120
> add CONCOURSE_CONTAINERD_CNI_PLUGINS_DIR

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Don't merge till https://github.com/concourse/concourse/pull/6079 is in
> allow configuring defaults for base resource types

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
- jobs/web/templates/pre_start.erb
concourse/concourse#6103
Also ran the envgen script and noticed a missing BASE_RESOURCE_TYPE_DEFAULTS line
> Add Honeycomb.io tracing

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
> add build events bigint migration config

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
for service name & attributes, and for OTLP.
> add new tracing configs

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Concourse PR is https://github.com/concourse/concourse/pull/6271
> add a new flag enable-skip-checking-not-in-use-resources

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
> Add vault timeout flags + var_source GC interval

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
- jobs/web/templates/pre_start.erb
added in concourse/concourse#6355
> Add CONCOURSE_TLS_CA_CERT flag

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
Signed-off-by: Esteban Foronda <eforonda@vmware.com>
Co-authored-by: Aidan Oldershaw <aoldershaw@pivotal.io>
> add params for MTU + external IP

- jobs/web/spec
> docs: fix build_log_retention.default_builds description

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Co-authored-by: Esteban Foronda <eforonda@vmware.com>
> [master] add ldap password connector flags

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Co-authored-by: Esteban Foronda <eforonda@vmware.com>
> [release/7.2.x] add ldap password connector flags

- jobs/bbr-atcdb/templates/config.json.erb
- jobs/bbr-atcdb/templates/connection_data.erb
- jobs/bbr-atcdb/templates/connection_data.erb.tmpl
- scripts/generate-job-templates
- tmpl/postgres_config.erb.tmpl
Also updated the `.tmpl` files which weren't updated in a few cases.
> Fix bbr ssl mode

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
part of concourse/concourse#6720
Signed-off-by: Muntasir Chowdhury <mchowdhury@pivotal.io>
> add CONCOURSE_CONTAINERD_ALLOW_HOST_ACCESS

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
https://github.com/concourse/concourse/pull/7125
> add properties for resource causality

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
> add datadog UDS filepath

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
fix https://ci.concourse-ci.org/teams/main/pipelines/release/jobs/bosh-check-props/builds/3?vars.version=%227.4.x%22
> add datadog UDS filepath to 7.4.x

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
flags added in concourse/concourse#7487
> add trace flags to worker job

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Related to concourse/concourse#7876
> Add the --pause-pipelines-after flag

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
for env var added in https://github.com/concourse/concourse/pull/7928
> add aws secret manager shared secret template env var

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
refer to https://github.com/concourse/concourse/pull/8324
> add vault srv lookup env var

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
refer to https://github.com/concourse/concourse/pull/8353
> add oidc disable get userinfo flag

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Signed-off-by: Evan <chaol@vmware.com>
> Add check_container_placement_strategy.

- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
> Add worker containerd config to v7.9.x

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
refer to https://github.com/concourse/concourse/pull/8709
> Add num-goroutine-threshold configuration

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
Account for changes introduced in https://github.com/concourse/concourse/pull/8899
> Add Vault token path config option

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
For PR https://github.com/concourse/concourse/pull/8381
> add CONCOURSE_RESOURCE_TYPE_CHECKING_INTERVAL

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
- jobs/worker/spec
- jobs/worker/templates/env.sh.erb
* Removed CONCOURSE_POSTGRES_BINARY_PARAMETERS because we switched to pgx
* Added CONCOURSE_STRICT_TRANSPORT_SECURITY
* Added CONCOURSE_CONTAINERD_PRIVILEGED_MODE
Related to concourse/concourse#9147
> Update env vars

- jobs/web/spec
- jobs/web/templates/bpm.yml.erb
- jobs/worker/templates/env.sh.erb
Related to https://github.com/concourse/concourse/issues/9242
> Add identity token and ssl negotation params
